import { collection, deleteDoc, doc, getDocs, query, setDoc, updateDoc, where } from 'firebase/firestore';
import { firestore } from './firebase';
import { getHostBookings, type Booking } from './bookings';

export type CleaningTicketType = 'pre_checkin' | 'post_checkout';
export type CleaningTicketStatus = 'open' | 'done';

export interface CleaningTicket {
  id: string;
  bookingId: string;
  propertyId: string;
  hostId: string;
  date: string;
  type: CleaningTicketType;
  status: CleaningTicketStatus;
  autoGenerated: boolean;
  updatedAt: string;
}

const cleaningCollection = collection(firestore, 'cleaningTickets');

function toIso(date: Date): string {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function parseIso(value: string): Date {
  const [year, month, day] = value.split('-').map(Number);
  return new Date(year, month - 1, day);
}

function shiftIso(value: string, days: number): string {
  const date = parseIso(value);
  date.setDate(date.getDate() + days);
  return toIso(date);
}

function ticketId(bookingId: string, type: CleaningTicketType): string {
  return `${bookingId}_${type}`;
}

function buildTicketsForBooking(booking: Booking): CleaningTicket[] {
  if (!booking.id) return [];

  const common = {
    bookingId: booking.id,
    propertyId: booking.propertyId,
    hostId: booking.hostId,
    status: 'open' as CleaningTicketStatus,
    autoGenerated: true,
    updatedAt: new Date().toISOString(),
  };

  return [
    {
      id: ticketId(booking.id, 'pre_checkin'),
      ...common,
      date: shiftIso(booking.startDate, -1),
      type: 'pre_checkin',
    },
    {
      id: ticketId(booking.id, 'post_checkout'),
      ...common,
      date: booking.endDate,
      type: 'post_checkout',
    },
  ];
}

export async function getHostCleaningTickets(hostId: string): Promise<CleaningTicket[]> {
  const q = query(cleaningCollection, where('hostId', '==', hostId));
  const snapshot = await getDocs(q);

  return snapshot.docs
    .map((docSnap) => ({ id: docSnap.id, ...(docSnap.data() as Omit<CleaningTicket, 'id'>) }))
    .sort((a, b) => a.date.localeCompare(b.date));
}

export async function syncCleaningTicketsForHost(hostId: string): Promise<void> {
  const [bookings, existingTickets] = await Promise.all([
    getHostBookings(hostId),
    getHostCleaningTickets(hostId),
  ]);

  const desiredTickets = bookings
    .filter((booking) => booking.status !== 'cancelled')
    .flatMap((booking) => buildTicketsForBooking(booking));

  const desiredMap = new Map(desiredTickets.map((ticket) => [ticket.id, ticket]));

  await Promise.all(
    desiredTickets.map((ticket) =>
      setDoc(doc(cleaningCollection, ticket.id), ticket, { merge: true }),
    ),
  );

  const staleTickets = existingTickets.filter(
    (ticket) => ticket.autoGenerated && !desiredMap.has(ticket.id),
  );

  await Promise.all(staleTickets.map((ticket) => deleteDoc(doc(cleaningCollection, ticket.id))));
}

export async function updateCleaningTicketStatus(ticketId: string, status: CleaningTicketStatus): Promise<void> {
  await updateDoc(doc(cleaningCollection, ticketId), {
    status,
    updatedAt: new Date().toISOString(),
  });
}
